# Generated by Django 2.2.3 on 2020-06-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='rest_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
