# Generated by Django 2.2.3 on 2020-06-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_storage', '0002_image_rest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
