# Generated by Django 2.2.3 on 2020-06-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_storage', '0004_auto_20200609_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='rest_name',
        ),
    ]
